# docker compose configuration for a fully contanerized build
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./images:/images
    ports:
      - 3000:3000
    depends_on:
      - db
