# docker compose configuration for local development
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    # envvars are read from the .env file
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
