version: "3.9"

services:
  db:
    image: postgres
    restart: always
    # envvars are read from the .env file
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./images:/app/images
    ports:
      - 3000:3000
    depends_on:
      - db
